// <auto-generated />
using System;
using FreeCakeTopper.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FreeCakeTopper.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211215161158_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("FreeCakeTopper.WebAPI.Models.TopperName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Font")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TopperNames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Blue",
                            Font = "Arial",
                            Name = "João",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "Orange",
                            Font = "Bonita",
                            Name = "Leo",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "Red",
                            Font = "Helvetica",
                            Name = "João",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Color = "Blue",
                            Font = "Helvetica",
                            Name = "Bale",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Color = "Black",
                            Font = "Arial",
                            Name = "Tarc",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Color = "Gray",
                            Font = "Bonita",
                            Name = "Jaspin",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("FreeCakeTopper.WebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jose@gmail.com",
                            Name = "José",
                            Password = "123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "fred@gmail.com",
                            Name = "Fred",
                            Password = "fred13"
                        },
                        new
                        {
                            Id = 3,
                            Email = "bia@gmail.com",
                            Name = "Bia",
                            Password = "suco13"
                        });
                });

            modelBuilder.Entity("FreeCakeTopper.WebAPI.Models.UserTopper", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopperId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TopperNameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "TopperId");

                    b.HasIndex("TopperNameId");

                    b.ToTable("UserToppers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            TopperId = 1
                        },
                        new
                        {
                            UserId = 1,
                            TopperId = 2
                        },
                        new
                        {
                            UserId = 2,
                            TopperId = 3
                        },
                        new
                        {
                            UserId = 2,
                            TopperId = 4
                        },
                        new
                        {
                            UserId = 3,
                            TopperId = 5
                        },
                        new
                        {
                            UserId = 3,
                            TopperId = 6
                        });
                });

            modelBuilder.Entity("FreeCakeTopper.WebAPI.Models.TopperName", b =>
                {
                    b.HasOne("FreeCakeTopper.WebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreeCakeTopper.WebAPI.Models.UserTopper", b =>
                {
                    b.HasOne("FreeCakeTopper.WebAPI.Models.TopperName", null)
                        .WithMany("UserToppers")
                        .HasForeignKey("TopperNameId");

                    b.HasOne("FreeCakeTopper.WebAPI.Models.User", null)
                        .WithMany("UserToppers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreeCakeTopper.WebAPI.Models.TopperName", b =>
                {
                    b.Navigation("UserToppers");
                });

            modelBuilder.Entity("FreeCakeTopper.WebAPI.Models.User", b =>
                {
                    b.Navigation("UserToppers");
                });
#pragma warning restore 612, 618
        }
    }
}
